### ISSUE TITLE
Rails generator should humanize enum key for default I18n value

### ISSUE THREAD

**Issue by masterT** [lucascaton/enumerate_it#100]
```
rails generate enumerate_it:enum foo_type bar_baz
      create  config/locales/foo_type.yml
      create  app/enumerations/foo_type.rb
```

```yml
# config/locales/foo_type.yml
en:
  enumerations:
    foo_type:
      bar_baz: 'Bar_baz'
```

I would expect the value for `bar_baz` to be [humanize](https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-humanize): `'Bar baz'` instead of `'Bar_baz'`.

```ruby
"bar_baz".humanize
# => "Bar baz"
```
