### ISSUE TITLE
Translate is not working with namespaced enumeration

### ISSUE THREAD

**Issue by andrecavallari** [lucascaton/enumerate_it#73]
The translate for namespaced enumeration is not working, any workaround for it?

* At least when use Namespace::EnumerationClass.to_a in the view...

**Comment by lucascaton** [comment]
Hi @andrecavallari,

Let's say you have a `Design::Color` enumeration class. You can create a locale file with the following content:

```yaml
pt-BR:
  enumerations:
    'design/color':
      blue: Azul
      red: Vermelho
```

Hope it helps :)
